### ISSUE TITLE
function "deploy"

### ISSUE THREAD

**Issue by CrazyDoc** [hiqdev/asset-packagist.dev#7]
hi. I tried to follow your installation instructions and this is what happened at the deploy step:

`[centos]$ ./vendor/bin/hidev deploy
yii\base\InvalidRouteException: Unable to resolve the request "deploy". in /home/centos/dir/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /home/centos/dir/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('deploy', Array)
#1 /home/centos/dir/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('deploy', Array)
#2 /home/centos/dir/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(hidev\components\Request))
#3 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(24): yii\base\Application->run()
#4 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(27): {closure}()
#5 {main}

Next yii\console\UnknownCommandException: Unknown command "deploy". in /home/centos/dir/vendor/yiisoft/yii2/console/Application.php:183
Stack trace:
#0 /home/centos/dir/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('deploy', Array)
#1 /home/centos/dir/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(hidev\components\Request))
#2 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(24): yii\base\Application->run()
#3 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(27): {closure}()
#4 {main}
Unknown command: deploy
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "deploy".'

in /home/centos/dir/vendor/yiisoft/yii2/base/Module.php:537

Stack trace:
#0 /home/centos/dir/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('deploy', Array)
#1 /home/centos/dir/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('deploy', Array)
#2 /home/centos/dir/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(hidev\components\Request))
#3 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(24): yii\base\Application->run()
#4 /home/centos/dir/vendor/hiqdev/hidev/bin/hidev(27): {closure}()
#5 {main}
`

could you tell me what's wrong? 
thanks

**Comment by hiqsol** [comment]
Unfortunately, the doc got expired.
